// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Configure(request: $models.ConfigureRequest): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1065098514, request);
}

export function FinalizeSession(sessionID: string): $CancellablePromise<$models.ExamReport> {
    return $Call.ByID(3685135372, sessionID);
}

export function GenerateSpeech(text: string): $CancellablePromise<$models.SpeechResponse> {
    return $Call.ByID(2776553183, text);
}

export function GetReport(sessionID: string): $CancellablePromise<$models.ExamReport> {
    return $Call.ByID(704064164, sessionID);
}

export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3018893939);
}

export function StartSession(config: $models.ExamConfig): $CancellablePromise<$models.StartSessionResponse> {
    return $Call.ByID(13616470, config);
}

export function SubmitAnswer(request: $models.SubmitAnswerRequest): $CancellablePromise<$models.SubmitAnswerResponse> {
    return $Call.ByID(665225252, request);
}

export function TestConnection(): $CancellablePromise<void> {
    return $Call.ByID(4037176558);
}
