// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
export {
    AppService
};

export type {
    AnswerEvaluation,
    AnswerRecord,
    AppSettings,
    ConfigureRequest,
    ExamConfig,
    ExamReport,
    OverallReport,
    Question,
    StartSessionResponse,
    SubmitAnswerRequest,
    SubmitAnswerResponse
} from "./models.js";
